export const data = {
  teamsCollection: {
    total: 9,
    skip: 0,
    limit: 100,
    items: [
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNXlCM1RmZFp4NU5LRE91cDNLZEgySQ==",
        id: 9,
        name: "Event Management Team",
        membersCollection: {
          total: 9,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNnFMRWROdVRQYUhaMnpDcDZ4b1U1Tg==",
              uid: 2024000004,
              name: "Annesha Das",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/annesha-das-86639428a",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/annesha_das_41",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvU2NQTjBFMWN2MkFlVTVjdzNnREU1",
              uid: 2024000003,
              name: "Arpita Paul",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/arpita-paul-483294289",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMVp2aXBOUXdSU1pRVEl2UDUyenlwQw==",
              uid: 2024000009,
              name: "Prachi Jha",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/prachi-jha-297b962b3",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMXFObG56VnZSYVlzVFd6ZGdPY2NUeA==",
              uid: 2024000006,
              name: "Sachin Gupta",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/sachin0811/",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNTdhVEswMXJTTmp3RzRFdWRjdVVyQQ==",
              uid: 2024000007,
              name: "Samim Biswas",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/samim-biswas-1a941817b",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNUZxWUJ6MGU5NzNtOXVWMFVjeFRwNA==",
              uid: 2024000011,
              name: "Sayan Paul",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/sayan-paul-b4940b255",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNjc5SW9OYlIxRXZ0ZExNWGdCczZVYg==",
              uid: 2024000010,
              name: "Shekhar Shubham Thakur",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/shekhar-shubham-010692274",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvM2JSb2VSTzlKbExjeTBLMXE4V1Y3bQ==",
              uid: 2024000008,
              name: "Sneha Karmakar",
              role: "Event Management Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/snehak993",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMXZmak9vNVhWRlMzRXdqUWZ2dW9SVA==",
              uid: 2024000005,
              name: "Soumili Saha",
              role: "Event Management Team Member ",
              bio: null,
              linkedin: "https://www.linkedin.com/in/soumili-saha-80b927272",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMmRLem9rMjI0eW9OcDM2VXgwMEhNdQ==",
        id: 8,
        name: "Outreach Team",
        membersCollection: {
          total: 1,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNnRyRmVPY2V3bDRPbWRWOUFMREhPSg==",
              uid: 2024000020,
              name: "Tamoghni Mukherjee",
              role: "Outreach Team Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/tamoghni-mukherjee-2a5881289",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNlhtRkl5ZlJQUGd2bjh3WWMxR0JsVw==",
        id: 7,
        name: "PR & Social Media Team",
        membersCollection: {
          total: 4,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvM0ZIRFdvY3dtU0tWNlpOM2ZSTTV3bw==",
              uid: 2024000023,
              name: "Adrija Karmakar",
              role: "PR & Social Media Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/adrija-karmakar-9a639028a",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/authentic_ahel",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNUc3RjBaUGNESTZOYU9wVndnckt3eQ==",
              uid: 2024000026,
              name: "Ankita Bera",
              role: "PR & Social Media Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/ankita-bera-3922a227a",
              github: null,
              twitter: "https://x.com/AnkitaBera2005",
              instagram: "https://www.instagram.com/ankita_bera.21",
              facebook:
                "https://www.facebook.com/share/3rPwn6VkzRsLYG79/?mibextid=qi2Omg",
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNkhKcmpEa1hJV21obUl4MFRJMnFrQg==",
              uid: 2024000024,
              name: "Bidish Chakraborty",
              role: "PR & Social Media Team Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/bidish-chakraborty-22653828a",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMjdheHpJMmxOY2I0QVN1S1BudklWbA==",
              uid: 2024000025,
              name: "Yashvi Dubey",
              role: "PR & Social Media Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/yashvi-dubey-b12638304",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMzkyNG9hdHNQYTdrc08wbzJlRG45WA==",
        id: 6,
        name: "Graphics Team",
        membersCollection: {
          total: 7,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMXY1R3V5RDVkaExMbVQ3eEpCdVJDMA==",
              uid: 2024000012,
              name: "Anindya Saha",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/anindya-saha-910750306",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/_ninja_x_naruto_",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNWk0eGVqa0NvaVJtNnNJa1h2TDFFYQ==",
              uid: 2024000016,
              name: "Anusha Gupta",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/anusha-gupta-735826284",
              github: "https://github.com/anushagupta11",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMTRwMGtUOTYzOUJlc29xeEpkY0MwVg==",
              uid: 2024000018,
              name: "Bindiya Mishra",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/bindiya-mishra-a38711303",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/mi_a_cara",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMnBLRGlRbGxGRzk1bHRFekpPaFdlOQ==",
              uid: 2024000017,
              name: "Shuvajit Chakraborty",
              role: "Graphics Team Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/shuvojit-chakraborty-661347320",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/s__chakraborty2005",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNFFPbzZzaXhLR2s0ZDBsUGF0a3hQdw==",
              uid: 2024000013,
              name: "Sinjini Ghosh",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/sinjini-ghosh-45b58a284",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNnJwS05ZQmxtTVFwdTQ0ZHN5cFhhSg==",
              uid: 2024000014,
              name: "Sneha Das",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/sneha-das-555570284/",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/this_is.sky",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNmI3ZW5FRXpyVXg0WVd6RDdSSDM2cQ==",
              uid: 2024000019,
              name: "Sneha Kundu",
              role: "Graphics Team Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/sneha-kundu-429488284",
              github: null,
              twitter: null,
              instagram: "https://www.instagram.com/serene_symphony07/",
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMWJuelZleU5sSm1PalhMRmwxQ2VMMQ==",
        id: 5,
        name: "Tech Team (Web Development)",
        membersCollection: {
          total: 6,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvWVplZzIwN25mOGZXdFduSkQxc3Vy",
              uid: 2024000036,
              name: "Aman Kumar Rai",
              role: "Web Development | Frontend",
              bio: null,
              linkedin: "https://www.linkedin.com/in/aman-rai-42742b27b",
              github: "https://github.com/AmanRai35",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNnJVR2I0RFlLWDYzek5BTE43RHhnag==",
              uid: 2024000039,
              name: "Debanjan Mondal",
              role: "DevOps | Full-Stack Dev",
              bio: null,
              linkedin: "https://www.linkedin.com/in/debanjanmondal2005/",
              github: "https://github.com/Debanjannnn",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvalZmd0VETzdWaWFHYVlpb1NrdnlL",
              uid: 2024000035,
              name: "Jyotipriya Biswas",
              role: "Web Development Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/jyotipriya-biswas-413990272",
              github: "https://github.com/noob-master-jpb",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvR0ZXTlhaN0V2ZWtpcllsSXIwZEp2",
              uid: 2024000040,
              name: "Manobendra Mandal",
              role: "Web Develoment Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/manobendra-mandal-513ba7214",
              github: "https://github.com/manovHacksaw",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNFpBcFc3Rmc4SzhlcG9PZFIxSlZ2Rg==",
              uid: 2024000037,
              name: "Monami Nandy",
              role: "Web Development | Frontend",
              bio: null,
              linkedin: "https://www.linkedin.com/in/monami-nandy-3b0802292",
              github: "https://github.com/monaminandy",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMlJ3aVFWWDg2bkx1V3hmVHFHTU0waQ==",
              uid: 2024000029,
              name: "Raj Sekhar Paul",
              role: "Web Development Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/raj-sekhar-paul-0064991ab/",
              github: "https://github.com/GalaxyBoy13",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNDdGNXRuRTM1blpiS09rUUhBQ3VFUA==",
        id: 4,
        name: "Tech Team (Cyber Security)",
        membersCollection: {
          total: 8,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvN2hUOUdwRTdURDUwdWxDOFQxVGMwVQ==",
              uid: 2024000033,
              name: "Arghyadeep Naskar",
              role: "Cyber Security Member",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/arghyadeep-naskar-aa60322bb/",
              github: "https://github.com/Eren64",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMWIzVlgzRlhmWXF0dUd3ZVpQR2lSMw==",
              uid: 2024000028,
              name: "Avik Samanta",
              role: "Cyber Security member | Shell",
              bio: null,
              linkedin: "https://www.linkedin.com/in/avik-samanta-00b98228a/",
              github: "https://github.com/avik-root",
              twitter: "https://x.com/ErrorXOX_404",
              instagram: "https://www.instagram.com/avik__samanta/",
              facebook: null,
              email: "official.aviksamanta@gmail.com",
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvV0tBalI3QzMzVkJUZDcxM012aTlV",
              uid: 2024000038,
              name: "Debangshu Roy",
              role: "Cyber Security Member | Network",
              bio: null,
              linkedin: "https://www.linkedin.com/in/debangshu-roy-773827254",
              github: "https://github.com/Debang5hu",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNEc3YjRvYkRCbmZRekxhWm1sQ0JMcA==",
              uid: 2024000032,
              name: "Gourav Kundu",
              role: "Cyber Security Member",
              bio: null,
              linkedin: "https://www.linkedin.com/in/gourav-kundu-788b35254",
              github: "https://github.com/grvknd",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNEF1elhDOE1VdVpzRkc4SFRmUWN2Qw==",
              uid: 2024000041,
              name: "Hritom Bhattacharya",
              role: "Cyber Security Member | Bug Bounty Hunter",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/hritom-bhattacharya-b0a3861a4",
              github: "https://github.com/Shadow-Spinner",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMXRETnQ5QlI2N253OHQwMVVnZkJZNw==",
              uid: 2024000030,
              name: "Praveen Joshi",
              role: "Cyber Security Member | Network",
              bio: null,
              linkedin: "https://www.linkedin.com/in/praveen-joshi-2b1271284",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvN0MyUHExUlFicHRidFBxVFc2Z2xlbQ==",
              uid: 2024000031,
              name: "Rajdeep Saha",
              role: "Cyber Security Member | Crypto",
              bio: null,
              linkedin: "https://www.linkedin.com/in/rajdeep-saha-476920278",
              github: "https://github.com/Rajtheboss23",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMkdCdXZMZ0hQQ1FEb05WRTdBbXlaZA==",
              uid: 2024000027,
              name: "Soumi Biswas",
              role: "Cyber Security Member | Crypto",
              bio: null,
              linkedin: "https://www.linkedin.com/in/soumi-biswas-09008b296",
              github: "https://github.com/Lonestar02",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMkpsbnhBMTFST2V6ckh3c2I4eTJRdQ==",
        id: 3,
        name: "Team Leads",
        membersCollection: {
          total: 4,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNTVMTmJVbXFFdEpmUUxnSDVlN0tjOA==",
              uid: 2024000022,
              name: "Adrija Ghosal",
              role: "PR & Social Media Lead ",
              bio: null,
              linkedin: "https://www.linkedin.com/in/adrija-ghosal-114b052b2",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvN0dpS2ZzMDQyODJLcTBTMnRhMFlENg==",
              uid: 2024000015,
              name: "Debankan Mullick",
              role: "Graphics Team Lead",
              bio: null,
              linkedin:
                "https://www.linkedin.com/in/debankan-mullick-1a1701245",
              github: "https://github.com/WakataZapaga",
              twitter: null,
              instagram: "https://www.instagram.com/senor_debankan/",
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvM0VxSmlXU0pMZUpEOWJjTkIycWd1Zw==",
              uid: 2024000034,
              name: "Krishnendu Das",
              role: "Web Development Lead",
              bio: null,
              linkedin: "https://linkedin.com/in/itskdhere",
              github: "https://github.com/itskdhere",
              twitter: "https://x.com/itskdhere",
              instagram: "https://www.instagram.com/itskdhere",
              facebook: "https://www.facebook.com/itskdhere",
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvN2xWVFFLMGE3UEMwSlhxUmhneUtTOQ==",
              uid: 2024000021,
              name: "Rima Bachar",
              role: "Outreach Lead",
              bio: null,
              linkedin: "https://www.linkedin.com/in/rima-bachar",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMUNnNDBMYmZ3WUdLVWFhTzdEdUpZcg==",
        id: 2,
        name: "Vice President",
        membersCollection: {
          total: 2,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNzFkNHFNdDNGa2RhRFVyTXlsNG9rcw==",
              uid: 2024000002,
              name: "Salini Dutta",
              role: "Vice President | Event Management Team",
              bio: null,
              linkedin: "https://www.linkedin.com/in/salini-dutta-87865a2aa",
              github: null,
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvNnVRbzRqUWI3NkdzYU5DdnBvYnRMUQ==",
              uid: 2024000001,
              name: "Soumyadeep Dutta",
              role: "Vice President | Cyber Security Lead",
              bio: null,
              linkedin: "https://linkedin.com/in/elli0t43",
              github: "https://github.com/elli0t43",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
      {
        _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvbkZqODJQODlTc1p0M241eTZoWlJ4",
        id: 1,
        name: "President",
        membersCollection: {
          total: 1,
          skip: 0,
          limit: 100,
          items: [
            {
              _id: "MTpjcm46Y29udGVudGZ1bDo6OmNvbnRlbnQ6c3BhY2VzLzR3aTg1c2Fic3QwYS9lbnZpcm9ubWVudHMvbWFzdGVyL2VudHJpZXMvMjJNUFJaZlVFWHNreGR3S3ZzVUNwaw==",
              uid: 2024000000,
              name: "Dibyataru Chakraborty",
              role: "Founder | President",
              bio: null,
              linkedin: "https://www.linkedin.com/in/dibyataru-chakraborty/",
              github: "https://github.com/Dibyataru-Chakraborty",
              twitter: null,
              instagram: null,
              facebook: null,
              email: null,
            },
          ],
        },
      },
    ],
  },
};
