// Avatar Map: https://github.com/mantinedev/mantine/tree/master/.demo/avatars
// M: 1 2 3            9 10
// F:       4 5 6 7 8

const teams = [
  {
    name: "Community Leads",
    hash: "leads",
    members: [
      {
        uid: "2024000000",
        hash: "e2fe35a8dc293e4665849c2b6238f65c",
        name: "Dibyataru Chakraborty",
        role: "President",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png",
        linkedin: "https://www.linkedin.com/in/dibyataru-chakraborty/",
        github: "https://github.com/Dibyataru-Chakraborty",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000002",
        hash: "b492d3ec56d0164fb5880c82f7b532ff",
        name: "Salini Dutta",
        role: "Vice President | Event Management Lead",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png",
        linkedin: "https://www.linkedin.com/in/salini-dutta-87865a2aa",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000001",
        hash: "3539d7522493d878b978cb936ad767ac",
        name: "Soumyadeep Dutta",
        role: "Vice President | Cyber Security Lead",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png",
        linkedin: "https://linkedin.com/in/elli0t43",
        github: "https://github.com/elli0t43",
        x: "",
        instagram: "",
      },
    ],
  },
  {
    name: "Tech Team (Cyber Security)",
    hash: "cyber-security",
    members: [
      {
        uid: "2024000033",
        hash: "ff40643541a1259194fb2b2ff1acfd20",
        name: "Arghyadeep Naskar",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/arghyadeep-naskar-aa60322bb/",
        github: "https://github.com/Eren64",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000028",
        hash: "c2e7f9af884fe492441fb40c7a2c68b2",
        name: "Avik Samanta",
        role: "Cyber Security, Shell",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
        email: "mailto:official.aviksamanta@gmail.com",
        linkedin: "https://www.linkedin.com/in/avik-samanta-00b98228a/",
        github: "https://github.com/avik-root",
        x: "https://x.com/ErrorXOX_404",
        instagram: "https://www.instagram.com/avik__samanta/",
      },
      {
        uid: "2024000038",
        hash: "ab17550238cba2da365a3b10e7ff908d",
        name: "Debangshu Roy",
        role: "Cyber Security, Network",
        bio: "I'm passionate about Ethical Hacking and Red Teaming.",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png",
        linkedin: "https://www.linkedin.com/in/debangshu-roy-773827254",
        github: "https://github.com/Debang5hu",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000032",
        hash: "d5d59cb5642195cd22dcb4bd239776b3",
        name: "Gourav Kundu",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/gourav-kundu-788b35254",
        github: "https://github.com/grvknd",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000041",
        hash: "08de5e2e6d11bd71bce504ecbcc8cbf9",
        name: "Hritom Bhattacharya",
        role: "Cyber Security, Bug Bounty Hunter",
        bio: "I am just inquisitive about loopholes in the technologies",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
        linkedin: "https://www.linkedin.com/in/hritom-bhattacharya-b0a3861a4",
        github: "https://github.com/Shadow-Spinner",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000030",
        hash: "30a010531521d0a5b0163a6381ef0f09",
        name: "Praveen Joshi",
        role: "Cyber Security, Network",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png",
        linkedin: "https://www.linkedin.com/in/praveen-joshi-2b1271284",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000031",
        hash: "12c7de641a146e989cda04029ea46deb",
        name: "Rajdeep Saha",
        role: "Cyber Security, Crypto",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/rajdeep-saha-476920278",
        github: "https://github.com/Rajtheboss23",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000027",
        hash: "fe3cf15e5ecb70b5c9bb7c88282c756f",
        name: "Soumi Biswas",
        role: "Cyber Security, Crypto",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png",
        linkedin: "https://www.linkedin.com/in/soumi-biswas-09008b296",
        github: "https://github.com/Lonestar02",
        x: "",
        instagram: "",
      },
    ],
  },
  {
    name: "Tech Team (Web Development)",
    hash: "web-dev",
    members: [
      {
        uid: "2024000036",
        hash: "2b03fced9fa87b32224f5661a5e098f2",
        name: "Aman Kumar Rai",
        role: "Web Dev, Frontend",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/aman-rai-42742b27b",
        github: "https://github.com/AmanRai35",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000039",
        hash: "5e2f3320c98771b70975443236677d65",
        name: "Debanjan Mondal",
        role: "DevOps, Full-Stack Dev",
        bio: "Full Stack Dev",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png",
        linkedin: "https://www.linkedin.com/in/debanjanmondal2005/",
        github: "https://github.com/Debanjannnn",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000035",
        hash: "57a5199f509337f1806c9f90dd7a6bf9",
        name: "Jyotipriya Biswas",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png",
        linkedin: "https://www.linkedin.com/in/jyotipriya-biswas-413990272",
        github: "https://github.com/noob-master-jpb",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000034",
        hash: "d0e51966575d9a50cd38b3bf0213dea4",
        name: "Krishnendu Das",
        role: "Web Dev Lead",
        bio: "Developer etc.",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
        linkedin: "https://linkedin.com/in/itskdhere",
        github: "https://github.com/itskdhere",
        x: "https://x.com/itskdhere",
        instagram: "https://www.instagram.com/itskdhere",
        facebook: "https://www.facebook.com/itskdhere",
      },
      {
        uid: "2024000040",
        hash: "8557e7f2efe2bacd6e3a56e00819d93c",
        name: "Manobendra Mandal",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/manobendra-mandal-513ba7214",
        github: "https://github.com/manovHacksaw",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000037",
        hash: "698b20aa9c857a7cad4e90b4bebc76cd",
        name: "Monami Nandy",
        role: "Web Dev, Frontend",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png",
        linkedin: "https://www.linkedin.com/in/monami-nandy-3b0802292",
        github: "https://github.com/monaminandy",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000029",
        hash: "508547454b1dbf5b0e24995d401aad19",
        name: "Raj Sekhar Paul",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png",
        linkedin: "https://www.linkedin.com/in/raj-sekhar-paul-0064991ab/",
        github: "https://github.com/GalaxyBoy13",
        x: "",
        instagram: "",
      },
    ],
  },
  {
    name: "Event Management Team",
    hash: "event-management",
    members: [
      {
        uid: "2024000004",
        hash: "a2b9cf463642bc304672714af780e477",
        name: "Annesha Das",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png",
        linkedin: "https://www.linkedin.com/in/annesha-das-86639428a",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/annesha_das_41",
      },
      {
        uid: "2024000003",
        hash: "4b0b423663965afdab92a5efb7a7cff9",
        name: "Arpita Paul",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png",
        linkedin: "https://www.linkedin.com/in/arpita-paul-483294289",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000009",
        hash: "768e7884f43a70f8f7022a74c5296848",
        name: "Prachi Jha",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png",
        linkedin: "https://www.linkedin.com/in/prachi-jha-297b962b3",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000006",
        hash: "8fa96e673ee04b1ca47f2c00d13d16fd",
        name: "Sachin Gupta",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png",
        linkedin: "https://www.linkedin.com/in/sachin0811/",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000007",
        hash: "fd8f9822f45df667fc9aed32d2495269",
        name: "Samim Biswas",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
        linkedin: "https://www.linkedin.com/in/samim-biswas-1a941817b",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000011",
        hash: "c13b15810c738de909e43798e8bf5663",
        name: "Sayan Paul",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/sayan-paul-b4940b255",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000010",
        hash: "57c65f0abfcf6aef1d0e6a00f8ed760b",
        name: "Shekhar Shubham Thakur",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-9.png",
        linkedin: "https://www.linkedin.com/in/shekhar-shubham-010692274",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000008",
        hash: "59da632e1037c3c9f8d108b6794bdcfb",
        name: "Sneha Karmakar",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png",
        linkedin: "https://www.linkedin.com/in/snehak993",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000005",
        hash: "59df927e83afdcbf2997d2d956d6d459",
        name: "Soumili Saha",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png",
        linkedin: "https://www.linkedin.com/in/soumili-saha-80b927272",
        github: "",
        x: "",
        instagram: "",
      },
    ],
  },
  {
    name: "Graphics Team",
    hash: "graphics",
    members: [
      {
        uid: "2024000012",
        hash: "5e933d817e1bd0313821862c39e8c360",
        name: "Anindya Saha",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
        linkedin: "https://www.linkedin.com/in/anindya-saha-910750306",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/_ninja_x_naruto_",
      },
      {
        uid: "2024000016",
        hash: "522f54a8ca9159a8b746bd96b295b5e2",
        name: "Anusha Gupta",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png",
        linkedin: "https://www.linkedin.com/in/anusha-gupta-735826284",
        github: "https://github.com/anushagupta11",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000018",
        hash: "2a2fbfb6e67752b5f29974327d5cc5ce",
        name: "Bindiya Mishra",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png",
        linkedin: "https://www.linkedin.com/in/bindiya-mishra-a38711303",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/mi_a_cara",
      },
      {
        uid: "2024000015",
        hash: "a0e379362044c9922068cf3979c36106",
        name: "Debankan Mullick",
        role: "Graphics Lead",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png",
        linkedin: "https://www.linkedin.com/in/debankan-mullick-1a1701245",
        github: "https://github.com/WakataZapaga",
        x: "",
        instagram: "https://www.instagram.com/senor_debankan/",
      },
      {
        uid: "2024000017",
        hash: "2a0f9537b8f8ff91052370589655fb2d",
        name: "Shuvajit Chakraborty",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
        linkedin: "https://www.linkedin.com/in/shuvojit-chakraborty-661347320",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/s__chakraborty2005",
      },
      {
        uid: "2024000013",
        hash: "323712f23f8392f822a5bb58b235cb64",
        name: "Sinjini Ghosh",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png",
        linkedin: "https://www.linkedin.com/in/sinjini-ghosh-45b58a284",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000014",
        hash: "30bfb2799a4d822f3f9aed83e41ba56b",
        name: "Sneha Das",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png",
        linkedin: "https://www.linkedin.com/in/sneha-das-555570284/",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/this_is.sky",
      },
      {
        uid: "2024000019",
        hash: "14f9ac14726e02abbe114873d623a60e",
        name: "Sneha Kundu",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png",
        linkedin: "https://www.linkedin.com/in/sneha-kundu-429488284",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/serene_symphony07/",
      },
    ],
  },
  {
    name: "Outreach Team",
    hash: "outreach",
    members: [
      {
        uid: "2024000021",
        hash: "815d8920c5085ac07ffdf20745909a58",
        name: "Rima Bachar",
        role: "Outreach Lead",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png",
        linkedin: "https://www.linkedin.com/in/rima-bachar",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000020",
        hash: "f94fab0d09b37c6f382917e175b80c68",
        name: "Tamoghni Mukherjee",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png",
        linkedin: "https://www.linkedin.com/in/tamoghni-mukherjee-2a5881289",
        github: "",
        x: "",
        instagram: "",
      },
    ],
  },
  {
    name: "PR & Social Media Team",
    hash: "pr",
    members: [
      {
        uid: "2024000022",
        hash: "79e44076d308c0b3ab0c6ce89a186b6e",
        name: "Adrija Ghosal",
        role: "PR & Social Media Lead",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-4.png",
        linkedin: "https://www.linkedin.com/in/adrija-ghosal-114b052b2",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000023",
        hash: "b3fc3af7715d8eb6a3c4d4448b41d670",
        name: "Adrija Karmakar",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-5.png",
        linkedin: "https://www.linkedin.com/in/adrija-karmakar-9a639028a",
        github: "",
        x: "",
        instagram: "https://www.instagram.com/authentic_ahel",
      },
      {
        uid: "2024000026",
        hash: "53baa5b252383aecbe966b18399d57eb",
        name: "Ankita Bera",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-6.png",
        linkedin: "https://www.linkedin.com/in/ankita-bera-3922a227a",
        github: "",
        x: "https://x.com/AnkitaBera2005",
        instagram: "https://www.instagram.com/ankita_bera.21",
        facebook:
          "https://www.facebook.com/share/3rPwn6VkzRsLYG79/?mibextid=qi2Omg",
      },
      {
        uid: "2024000024",
        hash: "027633a87ebd7b3b62179764bc6cea03",
        name: "Bidish Chakraborty",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png",
        linkedin: "https://www.linkedin.com/in/bidish-chakraborty-22653828a",
        github: "",
        x: "",
        instagram: "",
      },
      {
        uid: "2024000025",
        hash: "326af9c7386c1281f5e9271f418148e2",
        name: "Yashvi Dubey",
        role: ".",
        bio: "",
        avatar:
          "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-8.png",
        linkedin: "https://www.linkedin.com/in/yashvi-dubey-b12638304",
        github: "",
        x: "",
        instagram: "",
      },
    ],
  },
];

export default teams;
